"""
URL routing for Next 251 Media content app.
"""
from django.urls import path
from . import views

app_name = 'content'

urlpatterns = [
    path('', views.home, name='home'),
    path('articles/', views.post_list, name='post_list'),
    path('articles/<slug:slug>/', views.post_detail, name='post_detail'),
    path('articles/<slug:slug>/like/', views.post_like_toggle, name='post_like_toggle'),
    path('technology/', views.category_detail, kwargs={'slug': 'technology'}, name='category_technology'),
    path('ai/', views.category_detail, kwargs={'slug': 'ai'}, name='category_ai'),
    path('business/', views.category_detail, kwargs={'slug': 'business'}, name='category_business'),
    path('startups/', views.category_detail, kwargs={'slug': 'startups'}, name='category_startups'),
    path('innovation/', views.category_detail, kwargs={'slug': 'innovation'}, name='category_innovation'),
    path('topic/<slug:slug>/', views.category_detail, name='category_detail'),
    path('reviews/', views.review_list, name='review_list'),
    path('reviews/<slug:slug>/', views.review_detail, name='review_detail'),
    path('reviews/<slug:slug>/like/', views.review_like_toggle, name='review_like_toggle'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('newsletter/', views.newsletter_signup, name='newsletter_signup'),
    path('newsletter/archive/', views.newsletter_archive, name='newsletter_archive'),
    path('newsletter/<int:pk>/', views.newsletter_issue_detail, name='newsletter_issue_detail'),
    path('newsletter/<int:pk>/like/', views.newsletter_like_toggle, name='newsletter_like_toggle'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    # Writer interface (no Django admin)
    path('writer/posts/', views.writer_post_list, name='writer_post_list'),
    path('writer/posts/new/', views.writer_post_create, name='writer_post_create'),
    path('writer/posts/<int:pk>/edit/', views.writer_post_edit, name='writer_post_edit'),
    path('writer/reviews/', views.writer_review_list, name='writer_review_list'),
    path('writer/reviews/new/', views.writer_review_create, name='writer_review_create'),
    path('writer/reviews/<int:pk>/edit/', views.writer_review_edit, name='writer_review_edit'),
    # CMS: editor/admin manage posts, reviews, categories (in-site)
    path('manage/posts/', views.manage_post_list, name='manage_post_list'),
    path('manage/posts/new/', views.manage_post_create, name='manage_post_create'),
    path('manage/posts/<int:pk>/edit/', views.manage_post_edit, name='manage_post_edit'),
    path('manage/posts/<int:pk>/delete/', views.manage_post_delete, name='manage_post_delete'),
    path('manage/reviews/', views.manage_review_list, name='manage_review_list'),
    path('manage/reviews/new/', views.manage_review_create, name='manage_review_create'),
    path('manage/reviews/<int:pk>/edit/', views.manage_review_edit, name='manage_review_edit'),
    path('manage/reviews/<int:pk>/delete/', views.manage_review_delete, name='manage_review_delete'),
    path('manage/categories/', views.manage_category_list, name='manage_category_list'),
    path('manage/categories/new/', views.manage_category_create, name='manage_category_create'),
    path('manage/categories/<int:pk>/edit/', views.manage_category_edit, name='manage_category_edit'),
    path('manage/categories/<int:pk>/delete/', views.manage_category_delete, name='manage_category_delete'),
    path('manage/newsletter/', views.manage_newsletter_list, name='manage_newsletter_list'),
    path('manage/newsletter/sent/', views.manage_newsletter_sent_archive, name='manage_newsletter_sent_archive'),
    path('manage/newsletter/new/', views.manage_newsletter_create, name='manage_newsletter_create'),
    path('manage/newsletter/<int:pk>/edit/', views.manage_newsletter_edit, name='manage_newsletter_edit'),
    path('manage/newsletter/<int:pk>/delete/', views.manage_newsletter_delete, name='manage_newsletter_delete'),
    path('manage/newsletter/<int:pk>/post/', views.manage_newsletter_post, name='manage_newsletter_post'),
    path('manage/newsletter/<int:pk>/send/', views.manage_newsletter_send, name='manage_newsletter_send'),
    path('manage/newsletter/<int:pk>/resend/', views.manage_newsletter_resend, name='manage_newsletter_resend'),
    path('manage/newsletter/<int:pk>/unsend-to-posted/', views.manage_newsletter_unsend_to_posted, name='manage_newsletter_unsend_to_posted'),
    path('manage/newsletter/unsend-all-sent/', views.manage_newsletter_unsend_all_sent_to_posted, name='manage_newsletter_unsend_all_sent'),
    path('manage/newsletter/send-posted/', views.manage_newsletter_send_posted, name='manage_newsletter_send_posted'),
    path('manage/newsletter/send-daily-digest/', views.send_daily_digest, name='send_daily_digest'),
    path('manage/newsletter/send-weekly-digest/', views.send_weekly_digest, name='send_weekly_digest'),
]
