# Generated by Django 5.0.14

from django.db import migrations


def create_editor_writer_groups(apps, schema_editor):
    """Create Writers and Editors groups with appropriate permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get content app content types
    post_ct = ContentType.objects.get(app_label='content', model='post')
    review_ct = ContentType.objects.get(app_label='content', model='review')
    category_ct = ContentType.objects.get(app_label='content', model='category')
    newsletter_ct = ContentType.objects.get(app_label='content', model='newslettersubscriber')

    # Writers: can add and change own posts/reviews; view categories and newsletter
    writers, _ = Group.objects.get_or_create(name='Writers')
    writer_perms = Permission.objects.filter(
        content_type__in=[post_ct, review_ct, category_ct, newsletter_ct],
        codename__in=[
            'add_post', 'change_post', 'view_post',
            'add_review', 'change_review', 'view_review',
            'view_category', 'view_newslettersubscriber',
        ],
    )
    writers.permissions.set(writer_perms)

    # Editors: full content permissions (add, change, delete, view) for posts, reviews, categories, newsletter
    editors, _ = Group.objects.get_or_create(name='Editors')
    editor_perms = Permission.objects.filter(
        content_type__in=[post_ct, review_ct, category_ct, newsletter_ct],
    )
    editors.permissions.set(editor_perms)


def reverse_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Writers', 'Editors']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_author_review_author'),
    ]

    operations = [
        migrations.RunPython(create_editor_writer_groups, reverse_groups),
    ]
