# Generated by Django 5.0.14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_create_editor_writer_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who published this (editor or admin).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='published_posts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='review',
            name='published_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who published this (editor or admin).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='published_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
