# Generated by Django 5.0.14 on 2026-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_newsletter_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterissue',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When this was sent; null = draft.', null=True),
        ),
    ]
